USE testdb;
SET GLOBAL local_infile = ON;


-- No Indexing
EXPLAIN ANALYZE SELECT L.CITY, L.STATE, 
    			AVG(W.TAVG) AS Avg_Temp_F, 
			    SUM(W.PRCP) AS Total_Precip_Inches
FROM 
    LOCATIONS L
JOIN 
    (SELECT RND_LAT, RND_LNG, TAVG, PRCP
    FROM HISTORICAL_WEATHER
    WHERE H_MONTH IN (12, 1, 2)) W 
    	ON W.RND_LAT = L.RND_LAT
		AND W.RND_LNG = L.RND_LNG
GROUP BY 
    L.CITY, L.STATE
HAVING 
    AVG(W.TAVG) BETWEEN -100.0 AND 0.0 
    AND SUM(W.PRCP) > 200.0
ORDER BY 
    Avg_Temp_F DESC, Total_Precip_Inches ASC;



-- Add H_MONTH Indexing
CREATE INDEX idx_hmonth ON HISTORICAL_WEATHER (H_MONTH);
EXPLAIN ANALYZE SELECT L.CITY, L.STATE, 
    			AVG(W.TAVG) AS Avg_Temp_F, 
			    SUM(W.PRCP) AS Total_Precip_Inches
FROM 
    LOCATIONS L
JOIN 
    (SELECT RND_LAT, RND_LNG, TAVG, PRCP
    FROM HISTORICAL_WEATHER
    WHERE H_MONTH IN (12, 1, 2)) W 
    	ON W.RND_LAT = L.RND_LAT
		AND W.RND_LNG = L.RND_LNG
GROUP BY 
    L.CITY, L.STATE
HAVING 
    AVG(W.TAVG) BETWEEN -100.0 AND 0.0 
    AND SUM(W.PRCP) > 200.0
ORDER BY 
    Avg_Temp_F DESC, Total_Precip_Inches ASC;



-- ADD (TAVG, PRCP) Indexing
CREATE INDEX idx_tavg_prcp ON HISTORICAL_WEATHER (TAVG, PRCP);
EXPLAIN ANALYZE SELECT L.CITY, L.STATE, 
    			AVG(W.TAVG) AS Avg_Temp_F, 
			    SUM(W.PRCP) AS Total_Precip_Inches
FROM 
    LOCATIONS L
JOIN 
    (SELECT RND_LAT, RND_LNG, TAVG, PRCP
    FROM HISTORICAL_WEATHER
    WHERE H_MONTH IN (12, 1, 2)) W 
    	ON W.RND_LAT = L.RND_LAT
		AND W.RND_LNG = L.RND_LNG
GROUP BY 
    L.CITY, L.STATE
HAVING 
    AVG(W.TAVG) BETWEEN -100.0 AND 0.0 
    AND SUM(W.PRCP) > 200.0
ORDER BY 
    Avg_Temp_F DESC, Total_Precip_Inches ASC;



-- ADD (RND_LAT, RND_LNG) Indexing on HISTORICAL_WEATHER and LOCATIONS
CREATE INDEX idx_lat_long ON HISTORICAL_WEATHER (RND_LAT, RND_LNG);
CREATE INDEX idx_lat_long ON LOCATIONS (RND_LAT, RND_LNG);

SELECT L.CITY, L.STATE, 
    			AVG(W.TAVG) AS Avg_Temp_F, 
			    SUM(W.PRCP) AS Total_Precip
FROM 
    LOCATIONS L
JOIN 
    (SELECT RND_LAT, RND_LNG, TAVG, PRCP
    FROM HISTORICAL_WEATHER
    WHERE H_MONTH IN (12, 1, 2)) W 
    	ON W.RND_LAT = L.RND_LAT
		AND W.RND_LNG = L.RND_LNG
GROUP BY 
    L.CITY, L.STATE
HAVING 
    AVG(W.TAVG) BETWEEN -100.0 AND 0.0 
    AND SUM(W.PRCP) > 200.0
ORDER BY 
    Avg_Temp_F DESC, Total_Precip ASC;

DROP INDEX idx_hmonth ON HISTORICAL_WEATHER;
DROP INDEX idx_tavg_prcp ON HISTORICAL_WEATHER;
DROP INDEX idx_lat_long ON HISTORICAL_WEATHER;
