USE testdb;


-- Before Indexing
EXPLAIN ANALYZE SELECT L.CITY, L.STATE, AVG(H.PRCP) AS LOCATION_AVG_PRECIP
FROM LOCATIONS L
JOIN HISTORICAL_WEATHER H 
  ON L.RND_LAT = H.RND_LAT AND L.RND_LNG = H.RND_LNG
GROUP BY L.CITY, L.STATE
HAVING AVG(H.PRCP) > (
    SELECT AVG(PRCP)
    FROM HISTORICAL_WEATHER
)
ORDER BY LOCATION_AVG_PRECIP DESC;


-- Add RND_LAT, RND_LNG, PRCP Indexing
CREATE INDEX idx_hw_lat_lng_prcp ON HISTORICAL_WEATHER (RND_LAT, RND_LNG, PRCP);
EXPLAIN ANALYZE SELECT L.CITY, L.STATE, AVG(H.PRCP) AS LOCATION_AVG_PRECIP
FROM LOCATIONS L
JOIN HISTORICAL_WEATHER H 
  ON L.RND_LAT = H.RND_LAT AND L.RND_LNG = H.RND_LNG
GROUP BY L.CITY, L.STATE
HAVING AVG(H.PRCP) > (
    SELECT AVG(PRCP)
    FROM HISTORICAL_WEATHER
)
ORDER BY LOCATION_AVG_PRECIP DESC;


-- Add RND_LAT, RND_LNG Indexing
CREATE INDEX idx_loc_lat_lng ON LOCATIONS (RND_LAT, RND_LNG);
EXPLAIN ANALYZE SELECT L.CITY, L.STATE, AVG(H.PRCP) AS LOCATION_AVG_PRECIP
FROM LOCATIONS L
JOIN HISTORICAL_WEATHER H 
  ON L.RND_LAT = H.RND_LAT AND L.RND_LNG = H.RND_LNG
GROUP BY L.CITY, L.STATE
HAVING AVG(H.PRCP) > (
    SELECT AVG(PRCP)
    FROM HISTORICAL_WEATHER
)
ORDER BY LOCATION_AVG_PRECIP DESC;


-- Add PRCP Indexing 
CREATE INDEX idx_hw_prcp ON HISTORICAL_WEATHER (PRCP);
EXPLAIN ANALYZE SELECT L.CITY, L.STATE, AVG(H.PRCP) AS LOCATION_AVG_PRECIP
FROM LOCATIONS L
JOIN HISTORICAL_WEATHER H 
  ON L.RND_LAT = H.RND_LAT AND L.RND_LNG = H.RND_LNG
GROUP BY L.CITY, L.STATE
HAVING AVG(H.PRCP) > (
    SELECT AVG(PRCP)
    FROM HISTORICAL_WEATHER
)
ORDER BY LOCATION_AVG_PRECIP DESC;





DROP INDEX idx_hw_lat_lng_prcp ON HISTORICAL_WEATHER;
DROP INDEX idx_loc_lat_lng ON LOCATIONS;
DROP INDEX idx_hw_prcp ON HISTORICAL_WEATHER;


