USE testdb;
SET GLOBAL local_infile = ON;


-- Before Indexing
EXPLAIN ANALYZE SELECT L.CITY,L.STATE,AVG(S.TAVG) AS City_Avg_Summer_Temp
FROM LOCATIONS L
JOIN (SELECT RND_LAT,RND_LNG,TAVG FROM HISTORICAL_WEATHER WHERE H_MONTH IN (6,7,8)) S
  ON S.RND_LAT=L.RND_LAT AND S.RND_LNG=L.RND_LNG
GROUP BY L.CITY,L.STATE
HAVING AVG(S.TAVG) > (
  SELECT AVG(T.TAVG) FROM (SELECT TAVG FROM HISTORICAL_WEATHER WHERE H_MONTH IN (6,7,8)) T
)
ORDER BY City_Avg_Summer_Temp DESC;



-- Add H_MONTH, RND_LAT, RND_LNG, TAVG Indexing
CREATE INDEX idx_hw_month_lat_lng ON HISTORICAL_WEATHER (H_MONTH, RND_LAT, RND_LNG, TAVG);
EXPLAIN ANALYZE SELECT L.CITY,L.STATE,AVG(S.TAVG) AS City_Avg_Summer_Temp
FROM LOCATIONS L
JOIN (SELECT RND_LAT,RND_LNG,TAVG FROM HISTORICAL_WEATHER WHERE H_MONTH IN (6,7,8)) S
  ON S.RND_LAT=L.RND_LAT AND S.RND_LNG=L.RND_LNG
GROUP BY L.CITY,L.STATE
HAVING AVG(S.TAVG) > (
  SELECT AVG(T.TAVG) FROM (SELECT TAVG FROM HISTORICAL_WEATHER WHERE H_MONTH IN (6,7,8)) T
)
ORDER BY City_Avg_Summer_Temp DESC;


-- Add LOCATIONS RND_LAT, RND_LNG Indexing
CREATE INDEX idx_loc_lat_lng ON LOCATIONS (RND_LAT, RND_LNG);
EXPLAIN ANALYZE SELECT L.CITY,L.STATE,AVG(S.TAVG) AS City_Avg_Summer_Temp
FROM LOCATIONS L
JOIN (SELECT RND_LAT,RND_LNG,TAVG FROM HISTORICAL_WEATHER WHERE H_MONTH IN (6,7,8)) S
  ON S.RND_LAT=L.RND_LAT AND S.RND_LNG=L.RND_LNG
GROUP BY L.CITY,L.STATE
HAVING AVG(S.TAVG) > (
  SELECT AVG(T.TAVG) FROM (SELECT TAVG FROM HISTORICAL_WEATHER WHERE H_MONTH IN (6,7,8)) T
)
ORDER BY City_Avg_Summer_Temp DESC;


-- Add H_MONTH, TAVG Indexing
CREATE INDEX idx_hw_month_tavg ON HISTORICAL_WEATHER (H_MONTH, TAVG);
EXPLAIN ANALYZE SELECT L.CITY,L.STATE,AVG(S.TAVG) AS City_Avg_Summer_Temp
FROM LOCATIONS L
JOIN (SELECT RND_LAT,RND_LNG,TAVG FROM HISTORICAL_WEATHER WHERE H_MONTH IN (6,7,8)) S
  ON S.RND_LAT=L.RND_LAT AND S.RND_LNG=L.RND_LNG
GROUP BY L.CITY,L.STATE
HAVING AVG(S.TAVG) > (
  SELECT AVG(T.TAVG) FROM (SELECT TAVG FROM HISTORICAL_WEATHER WHERE H_MONTH IN (6,7,8)) T
)
ORDER BY City_Avg_Summer_Temp DESC;




DROP INDEX idx_hw_month_lat_lng ON HISTORICAL_WEATHER;
DROP INDEX idx_loc_lat_lng ON LOCATIONS;
DROP INDEX idx_hw_month_tavg ON HISTORICAL_WEATHER;
