USE testdb;

-- Before Indexing
EXPLAIN ANALYZE SELECT L.CITY,L.STATE
FROM LOCATIONS L
WHERE NOT EXISTS (
  SELECT 1
  FROM (SELECT RND_LAT,RND_LNG FROM HISTORICAL_WEATHER
        WHERE H_MONTH=10 AND H_DAY BETWEEN 20 AND 24
          AND (TAVG<150 OR TAVG>270 OR PRCP>1000)) S
  WHERE S.RND_LAT=L.RND_LAT AND S.RND_LNG=L.RND_LNG
);


-- ADD H_MONTH, H_DAY, RND_LAT, RND_LNG, TAVG, PRCP Indexing
CREATE INDEX idx_hw_oct_weather ON HISTORICAL_WEATHER (H_MONTH, H_DAY, RND_LAT, RND_LNG, TAVG, PRCP);
EXPLAIN ANALYZE SELECT L.CITY,L.STATE
FROM LOCATIONS L
WHERE NOT EXISTS (
  SELECT 1
  FROM (SELECT RND_LAT,RND_LNG FROM HISTORICAL_WEATHER
        WHERE H_MONTH=10 AND H_DAY BETWEEN 20 AND 24
          AND (TAVG<150 OR TAVG>270 OR PRCP>1000)) S
  WHERE S.RND_LAT=L.RND_LAT AND S.RND_LNG=L.RND_LNG
);



-- ADD RND_LAT, RND_LNG Indexing
CREATE INDEX idx_loc_lat_lng ON LOCATIONS (RND_LAT, RND_LNG);
EXPLAIN ANALYZE SELECT L.CITY,L.STATE
FROM LOCATIONS L
WHERE NOT EXISTS (
  SELECT 1
  FROM (SELECT RND_LAT,RND_LNG FROM HISTORICAL_WEATHER
        WHERE H_MONTH=10 AND H_DAY BETWEEN 20 AND 24
          AND (TAVG<150 OR TAVG>270 OR PRCP>1000)) S
  WHERE S.RND_LAT=L.RND_LAT AND S.RND_LNG=L.RND_LNG
);



-- ADD H_DAY, TAVG Indexing 
CREATE INDEX idx_hw_day_temp ON HISTORICAL_WEATHER (H_DAY, TAVG);
EXPLAIN ANALYZE SELECT L.CITY,L.STATE
FROM LOCATIONS L
WHERE NOT EXISTS (
  SELECT 1
  FROM (SELECT RND_LAT,RND_LNG FROM HISTORICAL_WEATHER
        WHERE H_MONTH=10 AND H_DAY BETWEEN 20 AND 24
          AND (TAVG<150 OR TAVG>270 OR PRCP>1000)) S
  WHERE S.RND_LAT=L.RND_LAT AND S.RND_LNG=L.RND_LNG
);


DROP INDEX idx_hw_oct_weather ON HISTORICAL_WEATHER;
DROP INDEX idx_loc_lat_lng ON LOCATIONS;
DROP INDEX idx_hw_day_temp ON HISTORICAL_WEATHER;
